// FUTBOL ARENASI PRO - DEVASA KARİYER VERİTABANI
const C = {
    GS: "superlig/galatasaray.football-logos.cc.png",
    FB: "superlig/fenerbahce.football-logos.cc.png",
    BJK: "superlig/besiktas.football-logos.cc.png",
    TS: "superlig/trabzonspor.football-logos.cc.png",
    IBFK: "superlig/basaksehir.football-logos.cc.png",
    KNY: "superlig/konyaspor.football-logos.cc.png",
    SAM: "superlig/samsunspor.football-logos.cc.png",
    GOZ: "superlig/goztepe-izmir.football-logos.cc.png",
    EYP: "superlig/eyupspor.football-logos.cc.png",
    KAS: "superlig/kasimpasa.football-logos.cc.png",
    RIZ: "superlig/rizespor.football-logos.cc.png",
    ALN: "superlig/alanyaspor.football-logos.cc.png",
    GFK: "superlig/gaziantep.football-logos.cc.png",
    AMD: "superlig/amed.football-logos.cc.png",
    KOC: "superlig/kocaelispor.football-logos.cc.png",
    GEN: "superlig/genclerbirligi.football-logos.cc.png",
    COR: "superlig/corum.football-logos.cc.png",
    ERZ: "superlig/erzurumspor.football-logos.cc.png",
    ADS: "https://ssl.gstatic.com/onebox/media/sports/logos/optimized/3-uB1F2K7aX_487nZ592qw_500x500.png",

    RM: "laliga/real-madrid.football-logos.cc.png",
    BAR: "laliga/barcelona.football-logos.cc.png",
    ATM: "laliga/atletico-madrid.football-logos.cc.png",
    SEV: "laliga/sevilla.football-logos.cc.png",
    VAL: "laliga/valencia.football-logos.cc.png",
    VIL: "laliga/villarreal.football-logos.cc.png",
    BIL: "laliga/athletic-club.football-logos.cc.png",
    RSO: "laliga/real-sociedad.football-logos.cc.png",

    ARS: "premierlig/arsenal.football-logos.cc.png",
    CHE: "premierlig/chelsea.football-logos.cc.png",
    LIV: "premierlig/liverpool.football-logos.cc.png",
    MCI: "premierlig/manchester-city.football-logos.cc.png",
    MUN: "premierlig/manchester-united.football-logos.cc.png",
    TOT: "premierlig/tottenham.football-logos.cc.png",
    AVL: "premierlig/aston-villa.football-logos.cc.png",
    NEW: "premierlig/newcastle.football-logos.cc.png",
    BHA: "premierlig/brighton.football-logos.cc.png",

    BAY: "Bundesliga/bayern-munchen.football-logos.cc.png",
    BVB: "Bundesliga/borussia-dortmund.football-logos.cc.png",
    B04: "Bundesliga/bayer-leverkusen.football-logos.cc.png",
    S04: "Bundesliga/schalke-04.football-logos.cc.png",
    RBL: "Bundesliga/rb-leipzig.football-logos.cc.png",
    SGE: "Bundesliga/eintracht-frankfurt.football-logos.cc.png",
    WOB: "Bundesliga/vfl-wolfsburg.football-logos.cc.png",

    INT: "Serie%20A/inter.football-logos.cc.png",
    MIL: "Serie%20A/milan.football-logos.cc.png",
    JUV: "Serie%20A/juventus.football-logos.cc.png",
    NAP: "Serie%20A/napoli.football-logos.cc.png",
    ROM: "Serie%20A/roma.football-logos.cc.png",
    LAZ: "Serie%20A/lazio.football-logos.cc.png",
    ATA: "Serie%20A/atalanta.football-logos.cc.png",
    FIO: "Serie%20A/fiorentina.football-logos.cc.png",

    PSG: "Ligue%201/paris-saint-germain.football-logos.cc.png",
    ASM: "Ligue%201/as-monaco.football-logos.cc.png",
    OM: "Ligue%201/marseille.football-logos.cc.png",
    OL: "Ligue%201/lyon.football-logos.cc.png",
    LOSC: "Ligue%201/lille.football-logos.cc.png",

    NAS: "Saudi%20Pro%20League/al-nassr.football-logos.cc.png",
    HIL: "Saudi%20Pro%20League/al-hilal.football-logos.cc.png",
    ITT: "Saudi%20Pro%20League/al-ittihad.football-logos.cc.png",
    AHL: "Saudi%20Pro%20League/al-ahli.football-logos.cc.png",

    POR: "https://crests.football-data.org/503.png",
    BEN: "https://crests.football-data.org/1903.png",
    SCP: "https://crests.football-data.org/498.png",
    AJA: "https://crests.football-data.org/678.png",
    PSV: "https://crests.football-data.org/674.png",
    FEY: "https://crests.football-data.org/675.png",
    TR: "https://flagcdn.com/w160/tr.png",
    BR: "https://flagcdn.com/w160/br.png",
    AR: "https://flagcdn.com/w160/ar.png",
    RU: "https://flagcdn.com/w160/ru.png"
};

const anaKariyerHavuzu = [
    { o: "Mauro Icardi 🇦🇷", k: [["Sampdoria", C.INT], ["Inter", C.INT], ["PSG", C.PSG], ["Galatasaray", C.GS]] },
    { o: "Victor Osimhen 🇳🇬", k: [["Wolfsburg", C.WOB], ["Charleroi", C.LOSC], ["Napoli", C.NAP], ["Galatasaray", C.GS]] },
    { o: "Edin Džeko 🇧🇦", k: [["Wolfsburg", C.WOB], ["Man City", C.MCI], ["Roma", C.ROM], ["Fenerbahçe", C.FB]] },
    { o: "Ciro Immobile 🇮🇹", k: [["Dortmund", C.BVB], ["Sevilla", C.SEV], ["Lazio", C.LAZ], ["Beşiktaş", C.BJK]] },
    { o: "Rafa Silva 🇵🇹", k: [["Feirense", C.POR], ["Braga", C.POR], ["Benfica", C.BEN], ["Beşiktaş", C.BJK]] },
    { o: "Michy Batshuayi 🇧🇪", k: [["Chelsea", C.CHE], ["Beşiktaş", C.BJK], ["Fenerbahçe", C.FB], ["Galatasaray", C.GS]] },
    { o: "Fred 🇧🇷", k: [["Internacional", C.BR], ["Shakhtar", C.AJA], ["Man United", C.MUN], ["Fenerbahçe", C.FB]] },
    { o: "Arda Güler 🇹🇷", k: [["Gençlerbirliği", C.GEN], ["Fenerbahçe", C.FB], ["Fenerbahçe", C.FB], ["Real Madrid", C.RM]] },
    { o: "Kerem Aktürkoğlu 🇹🇷", k: [["Başakşehir", C.IBFK], ["24 Erzincan", C.TR], ["Galatasaray", C.GS], ["Benfica", C.BEN]] },
    { o: "Ferdi Kadıoğlu 🇹🇷", k: [["NEC Nijmegen", C.PSV], ["Fenerbahçe", C.FB], ["Fenerbahçe", C.FB], ["Brighton", C.BHA]] },
    { o: "Dries Mertens 🇧🇪", k: [["Utrecht", C.PSV], ["PSV", C.PSV], ["Napoli", C.NAP], ["Galatasaray", C.GS]] },
    { o: "Hakim Ziyech 🇲🇦", k: [["Heerenveen", C.AJA], ["Ajax", C.AJA], ["Chelsea", C.CHE], ["Galatasaray", C.GS]] },
    { o: "Dušan Tadić 🇷🇸", k: [["Twente", C.AJA], ["Southampton", C.ARS], ["Ajax", C.AJA], ["Fenerbahçe", C.FB]] },
    { o: "Lucas Torreira 🇺🇾", k: [["Sampdoria", C.INT], ["Arsenal", C.ARS], ["Atl. Madrid", C.ATM], ["Galatasaray", C.GS]] },
    { o: "Mesut Özil 🇩🇪", k: [["Schalke 04", C.S04], ["Real Madrid", C.RM], ["Arsenal", C.ARS], ["Fenerbahçe", C.FB]] },
    { o: "Arda Turan 🇹🇷", k: [["Galatasaray", C.GS], ["Atl. Madrid", C.ATM], ["Barcelona", C.BAR], ["Başakşehir", C.IBFK]] },
    { o: "Wesley Sneijder 🇳🇱", k: [["Ajax", C.AJA], ["Real Madrid", C.RM], ["Inter", C.INT], ["Galatasaray", C.GS]] },
    { o: "Didier Drogba 🇨🇮", k: [["Marsilya", C.OM], ["Chelsea", C.CHE], ["Galatasaray", C.GS], ["Chelsea", C.CHE]] },
    { o: "Robin van Persie 🇳🇱", k: [["Feyenoord", C.FEY], ["Arsenal", C.ARS], ["Man United", C.MUN], ["Fenerbahçe", C.FB]] },
    { o: "Ricardo Quaresma 🇵🇹", k: [["Sporting CP", C.SCP], ["Barcelona", C.BAR], ["Inter", C.INT], ["Beşiktaş", C.BJK]] },
    { o: "Pepe 🇵🇹", k: [["Porto", C.POR], ["Real Madrid", C.RM], ["Beşiktaş", C.BJK], ["Porto", C.POR]] },
    { o: "Burak Yılmaz 🇹🇷", k: [["Beşiktaş", C.BJK], ["Fenerbahçe", C.FB], ["Trabzonspor", C.TS], ["Galatasaray", C.GS]] },
    { o: "Caner Erkin 🇹🇷", k: [["CSKA Moskova", C.RU], ["Galatasaray", C.GS], ["Fenerbahçe", C.FB], ["Beşiktaş", C.BJK]] },
    { o: "Alex de Souza 🇧🇷", k: [["Palmeiras", C.BR], ["Flamengo", C.BR], ["Parma", C.MIL], ["Fenerbahçe", C.FB]] },
    { o: "Gheorghe Hagi 🇷🇴", k: [["Steaua Bükreş", C.TR], ["Real Madrid", C.RM], ["Brescia", C.INT], ["Galatasaray", C.GS]] },
    { o: "Mario Balotelli 🇮🇹", k: [["Inter", C.INT], ["Man City", C.MCI], ["Milan", C.MIL], ["Adana Demir", C.ADS]] },
    { o: "José Sosa 🇦🇷", k: [["Bayern Münih", C.BAY], ["Atl. Madrid", C.ATM], ["Beşiktaş", C.BJK], ["Trabzonspor", C.TS]] },
    { o: "Talisca 🇧🇷", k: [["Bahia", C.BR], ["Benfica", C.BEN], ["Beşiktaş", C.BJK], ["Al-Nassr", C.NAS]] },
    { o: "Vincent Aboubakar 🇨🇲", k: [["Lorient", C.LOSC], ["Porto", C.POR], ["Beşiktaş", C.BJK], ["Al-Nassr", C.NAS]] },
    { o: "Felipe Melo 🇧🇷", k: [["Fiorentina", C.FIO], ["Juventus", C.JUV], ["Galatasaray", C.GS], ["Inter", C.INT]] },
    { o: "Nani 🇵🇹", k: [["Sporting CP", C.SCP], ["Man United", C.MUN], ["Fenerbahçe", C.FB], ["Valencia", C.VAL]] },
    { o: "Demba Ba 🇸🇳", k: [["Hoffenheim", C.BVB], ["Newcastle", C.NEW], ["Chelsea", C.CHE], ["Beşiktaş", C.BJK]] },
    { o: "Radamel Falcao 🇨🇴", k: [["Porto", C.POR], ["Atl. Madrid", C.ATM], ["Monaco", C.ASM], ["Galatasaray", C.GS]] },
    { o: "Nicolas Anelka 🇫🇷", k: [["Arsenal", C.ARS], ["Real Madrid", C.RM], ["Man City", C.MCI], ["Fenerbahçe", C.FB]] },
    { o: "Milan Baroš 🇨🇿", k: [["Liverpool", C.LIV], ["Aston Villa", C.AVL], ["Lyon", C.OL], ["Galatasaray", C.GS]] },
    { o: "Emre Belözoğlu 🇹🇷", k: [["Galatasaray", C.GS], ["Inter", C.INT], ["Newcastle", C.NEW], ["Fenerbahçe", C.FB]] },
    { o: "Gökhan Töre 🇹🇷", k: [["Hamburg", C.BVB], ["Rubin Kazan", C.RU], ["Beşiktaş", C.BJK], ["West Ham", C.ARS]] },
    { o: "Loris Karius 🇩🇪", k: [["Mainz", C.S04], ["Liverpool", C.LIV], ["Beşiktaş", C.BJK], ["Newcastle", C.NEW]] },
    { o: "Mamadou Niang 🇸🇳", k: [["Troyes", C.OM], ["Marsilya", C.OM], ["Fenerbahçe", C.FB], ["Beşiktaş", C.BJK]] },
    { o: "Elvir Baljić 🇧🇦", k: [["Bursaspor", C.TR], ["Fenerbahçe", C.FB], ["Real Madrid", C.RM], ["Galatasaray", C.GS]] },
    { o: "Kevin-Prince Boateng 🇬🇭", k: [["Tottenham", C.TOT], ["Milan", C.MIL], ["Barcelona", C.BAR], ["Beşiktaş", C.BJK]] },
    { o: "Hugo Rodallega 🇨🇴", k: [["Wigan", C.CHE], ["Fulham", C.CHE], ["Akhisar", C.TR], ["Trabzonspor", C.TS]] },
    { o: "Daniel Güiza 🇪🇸", k: [["Getafe", C.VAL], ["Mallorca", C.VAL], ["Fenerbahçe", C.FB], ["Getafe", C.VAL]] },
    { o: "Simon Kjær 🇩🇰", k: [["Wolfsburg", C.WOB], ["Lille", C.LOSC], ["Fenerbahçe", C.FB], ["Milan", C.MIL]] },
    { o: "Luiz Gustavo 🇧🇷", k: [["Hoffenheim", C.BVB], ["Bayern Münih", C.BAY], ["Marsilya", C.OM], ["Fenerbahçe", C.FB]] },
    { o: "Bafétimbi Gomis 🇫🇷", k: [["Saint-Etienne", C.OL], ["Lyon", C.OL], ["Marsilya", C.OM], ["Galatasaray", C.GS]] },
    { o: "Miralem Pjanić 🇧🇦", k: [["Lyon", C.OL], ["Roma", C.ROM], ["Juventus", C.JUV], ["Beşiktaş", C.BJK]] },
    { o: "Goran Pandev 🇲🇰", k: [["Lazio", C.LAZ], ["Inter", C.INT], ["Napoli", C.NAP], ["Galatasaray", C.GS]] },
    { o: "Steven Nzonzi 🇫🇷", k: [["Stoke City", C.CHE], ["Sevilla", C.SEV], ["Roma", C.ROM], ["Galatasaray", C.GS]] },
    { o: "Alex Telles 🇧🇷", k: [["Gremio", C.BR], ["Galatasaray", C.GS], ["Porto", C.POR], ["Man United", C.MUN]] },
    { o: "Marcao 🇧🇷", k: [["Chaves", C.POR], ["Galatasaray", C.GS], ["Galatasaray", C.GS], ["Sevilla", C.SEV]] },
    { o: "Kim Min-jae 🇰🇷", k: [["Beijing Guoan", C.FB], ["Fenerbahçe", C.FB], ["Napoli", C.NAP], ["Bayern Münih", C.BAY]] },
    { o: "Eljif Elmas 🇲🇰", k: [["Rabotnicki", C.FB], ["Fenerbahçe", C.FB], ["Napoli", C.NAP], ["RB Leipzig", C.RBL]] },
    { o: "Vedat Muriqi 🇽🇰", k: [["Giresunspor", C.TR], ["Ç. Rizespor", C.RIZ], ["Fenerbahçe", C.FB], ["Lazio", C.LAZ]] },
    { o: "Sörloth 🇳🇴", k: [["Crystal Palace", C.TOT], ["Trabzonspor", C.TS], ["RB Leipzig", C.RBL], ["Atl. Madrid", C.ATM]] },
    { o: "Yusuf Yazıcı 🇹🇷", k: [["Trabzonspor", C.TS], ["Lille", C.LOSC], ["CSKA Moskova", C.RU], ["Olympiakos", C.TS]] },
    { o: "Cenk Tosun 🇹🇷", k: [["Gaziantepspor", C.GFK], ["Beşiktaş", C.BJK], ["Everton", C.LIV], ["Fenerbahçe", C.FB]] },
    { o: "Salih Uçan 🇹🇷", k: [["Bucaspor", C.TR], ["Fenerbahçe", C.FB], ["Roma", C.ROM], ["Beşiktaş", C.BJK]] },
    { o: "Ozan Kabak 🇹🇷", k: [["Galatasaray", C.GS], ["Stuttgart", C.BVB], ["Schalke 04", C.S04], ["Liverpool", C.LIV]] },
    { o: "Merih Demiral 🇹🇷", k: [["Alanyaspor", C.ALN], ["Sassuolo", C.JUV], ["Juventus", C.JUV], ["Al-Ahli", C.AHL]] },
    { o: "Çağlar Söyüncü 🇹🇷", k: [["Altınordu", C.TR], ["Freiburg", C.BVB], ["Leicester", C.CHE], ["Atl. Madrid", C.ATM]] },
    { o: "Cengiz Ünder 🇹🇷", k: [["Başakşehir", C.IBFK], ["Roma", C.ROM], ["Marsilya", C.OM], ["Fenerbahçe", C.FB]] },

    // DÜNYA DEVLERİ & AVRUPA EFSANELERİ
    { o: "Kylian Mbappé 🇫🇷", k: [["Monaco", C.ASM], ["PSG", C.PSG], ["PSG", C.PSG], ["Real Madrid", C.RM]] },
    { o: "Cristiano Ronaldo 🇵🇹", k: [["Sporting CP", C.SCP], ["Man United", C.MUN], ["Real Madrid", C.RM], ["Al-Nassr", C.NAS]] },
    { o: "Lionel Messi 🇦🇷", k: [["Newell's", C.AR], ["Barcelona", C.BAR], ["PSG", C.PSG], ["Inter Miami", C.AR]] },
    { o: "Neymar Jr 🇧🇷", k: [["Santos", C.BR], ["Barcelona", C.BAR], ["PSG", C.PSG], ["Al-Hilal", C.HIL]] },
    { o: "Karim Benzema 🇫🇷", k: [["Lyon", C.OL], ["Real Madrid", C.RM], ["Real Madrid", C.RM], ["Al-Ittihad", C.ITT]] },
    { o: "Jude Bellingham 🏴󠁧󠁢󠁥󠁮󠁧󠁿", k: [["Birmingham", C.ARS], ["Dortmund", C.BVB], ["Dortmund", C.BVB], ["Real Madrid", C.RM]] },
    { o: "Erling Haaland 🇳🇴", k: [["Molde", C.MCI], ["Salzburg", C.BVB], ["Dortmund", C.BVB], ["Man City", C.MCI]] },
    { o: "Robert Lewandowski 🇵🇱", k: [["Lech Poznan", C.BVB], ["Dortmund", C.BVB], ["Bayern Münih", C.BAY], ["Barcelona", C.BAR]] },
    { o: "Zlatan Ibrahimović 🇸🇪", k: [["Ajax", C.AJA], ["Juventus", C.JUV], ["Inter", C.INT], ["Milan", C.MIL]] },
    { o: "Luis Suárez 🇺🇾", k: [["Ajax", C.AJA], ["Liverpool", C.LIV], ["Barcelona", C.BAR], ["Atl. Madrid", C.ATM]] },
    { o: "Gareth Bale 🏴󠁧󠁢󠁷󠁬󠁳󠁿", k: [["Southampton", C.ARS], ["Tottenham", C.TOT], ["Real Madrid", C.RM], ["Tottenham", C.TOT]] },
    { o: "Eden Hazard 🇧🇪", k: [["Lille", C.LOSC], ["Chelsea", C.CHE], ["Real Madrid", C.RM], ["Real Madrid", C.RM]] },
    { o: "Luka Modrić 🇭🇷", k: [["Dinamo Zagreb", C.TOT], ["Tottenham", C.TOT], ["Real Madrid", C.RM], ["Real Madrid", C.RM]] },
    { o: "Toni Kroos 🇩🇪", k: [["Hansa Rostock", C.BAY], ["Leverkusen", C.B04], ["Bayern Münih", C.BAY], ["Real Madrid", C.RM]] },
    { o: "Sergio Ramos 🇪🇸", k: [["Sevilla", C.SEV], ["Real Madrid", C.RM], ["PSG", C.PSG], ["Sevilla", C.SEV]] },
    { o: "Thiago Silva 🇧🇷", k: [["Fluminense", C.BR], ["Milan", C.MIL], ["PSG", C.PSG], ["Chelsea", C.CHE]] },
    { o: "Álvaro Morata 🇪🇸", k: [["Real Madrid", C.RM], ["Juventus", C.JUV], ["Chelsea", C.CHE], ["Milan", C.MIL]] },
    { o: "Romelu Lukaku 🇧🇪", k: [["Chelsea", C.CHE], ["Man United", C.MUN], ["Inter", C.INT], ["Napoli", C.NAP]] },
    { o: "João Félix 🇵🇹", k: [["Benfica", C.BEN], ["Atl. Madrid", C.ATM], ["Barcelona", C.BAR], ["Chelsea", C.CHE]] },
    { o: "Sadio Mané 🇸🇳", k: [["Metz", C.LOSC], ["Southampton", C.ARS], ["Liverpool", C.LIV], ["Al-Nassr", C.NAS]] },
    { o: "Alexis Sánchez 🇨🇱", k: [["Udinese", C.MIL], ["Barcelona", C.BAR], ["Arsenal", C.ARS], ["Inter", C.INT]] },
    { o: "Angel Di María 🇦🇷", k: [["Benfica", C.BEN], ["Real Madrid", C.RM], ["Man United", C.MUN], ["PSG", C.PSG]] },
    { o: "Cesc Fàbregas 🇪🇸", k: [["Arsenal", C.ARS], ["Barcelona", C.BAR], ["Chelsea", C.CHE], ["Monaco", C.ASM]] },
    { o: "Arturo Vidal 🇨🇱", k: [["Leverkusen", C.B04], ["Juventus", C.JUV], ["Bayern Münih", C.BAY], ["Barcelona", C.BAR]] },
    { o: "James Rodríguez 🇨🇴", k: [["Porto", C.POR], ["Monaco", C.ASM], ["Real Madrid", C.RM], ["Bayern Münih", C.BAY]] },
    { o: "Xabi Alonso 🇪🇸", k: [["Real Sociedad", C.RSO], ["Liverpool", C.LIV], ["Real Madrid", C.RM], ["Bayern Münih", C.BAY]] },
    { o: "Fernando Torres 🇪🇸", k: [["Atl. Madrid", C.ATM], ["Liverpool", C.LIV], ["Chelsea", C.CHE], ["Milan", C.MIL]] },
    { o: "Gonzalo Higuaín 🇦🇷", k: [["Real Madrid", C.RM], ["Napoli", C.NAP], ["Juventus", C.JUV], ["Chelsea", C.CHE]] },
    { o: "Thibaut Courtois 🇧🇪", k: [["Genk", C.CHE], ["Atl. Madrid", C.ATM], ["Chelsea", C.CHE], ["Real Madrid", C.RM]] },
    { o: "Keylor Navas 🇨🇷", k: [["Albacete", C.VAL], ["Levante", C.VAL], ["Real Madrid", C.RM], ["PSG", C.PSG]] },
    { o: "David Luiz 🇧🇷", k: [["Benfica", C.BEN], ["Chelsea", C.CHE], ["PSG", C.PSG], ["Arsenal", C.ARS]] },
    { o: "Willian 🇧🇷", k: [["Shakhtar", C.CHE], ["Chelsea", C.CHE], ["Arsenal", C.ARS], ["Fulham", C.CHE]] },
    { o: "Christian Eriksen 🇩🇰", k: [["Ajax", C.AJA], ["Tottenham", C.TOT], ["Inter", C.INT], ["Man United", C.MUN]] },
    { o: "Memphis Depay 🇳🇱", k: [["PSV", C.PSV], ["Man United", C.MUN], ["Lyon", C.OL], ["Atl. Madrid", C.ATM]] },
    { o: "Pierre-Emerick Aubameyang 🇬🇦", k: [["Dortmund", C.BVB], ["Arsenal", C.ARS], ["Barcelona", C.BAR], ["Marsilya", C.OM]] },
    { o: "Ivan Rakitić 🇭🇷", k: [["Schalke 04", C.S04], ["Sevilla", C.SEV], ["Barcelona", C.BAR], ["Al-Shabab", C.NAS]] },
    { o: "Mario Mandžukić 🇭🇷", k: [["Wolfsburg", C.WOB], ["Bayern Münih", C.BAY], ["Atl. Madrid", C.ATM], ["Juventus", C.JUV]] },
    { o: "Lassana Diarra 🇫🇷", k: [["Chelsea", C.CHE], ["Arsenal", C.ARS], ["Real Madrid", C.RM], ["PSG", C.PSG]] },
    { o: "Alexandre Pato 🇧🇷", k: [["Internacional", C.BR], ["Milan", C.MIL], ["Chelsea", C.CHE], ["Villarreal", C.VIL]] },
    { o: "Martin Braithwaite 🇩🇰", k: [["Toulouse", C.OL], ["Leganes", C.VAL], ["Barcelona", C.BAR], ["Gremio", C.BR]] },
    { o: "Eric Maxim Choupo-Moting 🇨🇲", k: [["Mainz", C.S04], ["Schalke 04", C.S04], ["PSG", C.PSG], ["Bayern Münih", C.BAY]] },
    { o: "Maxi López 🇦🇷", k: [["River Plate", C.AR], ["Barcelona", C.BAR], ["Milan", C.MIL], ["Sampdoria", C.INT]] },
    { o: "Pepe Reina 🇪🇸", k: [["Barcelona", C.BAR], ["Liverpool", C.LIV], ["Bayern Münih", C.BAY], ["Milan", C.MIL]] },
    { o: "Raheem Sterling 🏴󠁧󠁢󠁥󠁮󠁧󠁿", k: [["Liverpool", C.LIV], ["Man City", C.MCI], ["Chelsea", C.CHE], ["Arsenal", C.ARS]] },
    { o: "Kai Havertz 🇩🇪", k: [["Leverkusen", C.B04], ["Chelsea", C.CHE], ["Chelsea", C.CHE], ["Arsenal", C.ARS]] },
    { o: "Mason Mount 🏴󠁧󠁢󠁥󠁮󠁧󠁿", k: [["Vitesse", C.CHE], ["Derby", C.CHE], ["Chelsea", C.CHE], ["Man United", C.MUN]] },
    { o: "Declan Rice 🏴󠁧󠁢󠁥󠁮󠁧󠁿", k: [["Chelsea Genç", C.ARS], ["West Ham", C.ARS], ["West Ham", C.ARS], ["Arsenal", C.ARS]] },
    { o: "Jack Grealish 🏴󠁧󠁢󠁥󠁮󠁧󠁿", k: [["Notts County", C.AVL], ["Aston Villa", C.AVL], ["Aston Villa", C.AVL], ["Man City", C.MCI]] },
    { o: "Cole Palmer 🏴󠁧󠁢󠁥󠁮󠁧󠁿", k: [["Man City B", C.MCI], ["Man City", C.MCI], ["Man City", C.MCI], ["Chelsea", C.CHE]] },
    { o: "Kepa Arrizabalaga 🇪🇸", k: [["Athletic Bilbao", C.BIL], ["Chelsea", C.CHE], ["Real Madrid", C.RM], ["Bournemouth", C.CHE]] },
    { o: "Gabriel Jesus 🇧🇷", k: [["Palmeiras", C.BR], ["Man City", C.MCI], ["Man City", C.MCI], ["Arsenal", C.ARS]] },
    { o: "Oleksandr Zinchenko 🇺🇦", k: [["Ufa", C.MCI], ["PSV", C.PSV], ["Man City", C.MCI], ["Arsenal", C.ARS]] },
    { o: "Jorginho 🇮🇹", k: [["Verona", C.NAP], ["Napoli", C.NAP], ["Chelsea", C.CHE], ["Arsenal", C.ARS]] },
    { o: "Mateo Kovačić 🇭🇷", k: [["Inter", C.INT], ["Real Madrid", C.RM], ["Chelsea", C.CHE], ["Man City", C.MCI]] },
    { o: "Riyad Mahrez 🇩🇿", k: [["Le Havre", C.CHE], ["Leicester", C.CHE], ["Man City", C.MCI], ["Al-Ahli", C.AHL]] },
    { o: "N'Golo Kanté 🇫🇷", k: [["Boulogne", C.CHE], ["Leicester", C.CHE], ["Chelsea", C.CHE], ["Al-Ittihad", C.ITT]] },
    { o: "Aymeric Laporte 🇪🇸", k: [["Athletic Bilbao", C.BIL], ["Man City", C.MCI], ["Man City", C.MCI], ["Al-Nassr", C.NAS]] },
    { o: "Roberto Firmino 🇧🇷", k: [["Figueirense", C.BR], ["Hoffenheim", C.BVB], ["Liverpool", C.LIV], ["Al-Ahli", C.AHL]] },
    { o: "Fabinho 🇧🇷", k: [["Real Madrid B", C.RM], ["Monaco", C.ASM], ["Liverpool", C.LIV], ["Al-Ittihad", C.ITT]] },
    { o: "Jordan Henderson 🏴󠁧󠁢󠁥󠁮󠁧󠁿", k: [["Sunderland", C.LIV], ["Liverpool", C.LIV], ["Al-Ettifaq", C.NAS], ["Ajax", C.AJA]] },
    { o: "Kalidou Koulibaly 🇸🇳", k: [["Genk", C.NAP], ["Napoli", C.NAP], ["Chelsea", C.CHE], ["Al-Hilal", C.HIL]] },
    { o: "Sergej Milinković-Savić 🇷🇸", k: [["Vojvodina", C.LAZ], ["Genk", C.LAZ], ["Lazio", C.LAZ], ["Al-Hilal", C.HIL]] },
    { o: "Rúben Neves 🇵🇹", k: [["Porto", C.POR], ["Wolves", C.ARS], ["Wolves", C.ARS], ["Al-Hilal", C.HIL]] },
    { o: "Aleksandar Mitrović 🇷🇸", k: [["Anderlecht", C.NEW], ["Newcastle", C.NEW], ["Fulham", C.CHE], ["Al-Hilal", C.HIL]] },
    { o: "Yassine Bounou 🇲🇦", k: [["Girona", C.SEV], ["Sevilla", C.SEV], ["Sevilla", C.SEV], ["Al-Hilal", C.HIL]] },
    { o: "Franck Kessié 🇨🇮", k: [["Atalanta", C.ATA], ["Milan", C.MIL], ["Barcelona", C.BAR], ["Al-Ahli", C.AHL]] },
    { o: "Allan Saint-Maximin 🇫🇷", k: [["Nice", C.OM], ["Newcastle", C.NEW], ["Al-Ahli", C.AHL], ["Fenerbahçe", C.FB]] },
    { o: "Gabriel Paulista 🇧🇷", k: [["Villarreal", C.VIL], ["Arsenal", C.ARS], ["Valencia", C.VAL], ["Beşiktaş", C.BJK]] },
    { o: "Arthur Masuaku 🇨🇩", k: [["Valenciennes", C.OM], ["Olympiakos", C.BJK], ["West Ham", C.ARS], ["Beşiktaş", C.BJK]] },
    { o: "Alexander Djiku 🇬🇭", k: [["Bastia", C.LOSC], ["Caen", C.LOSC], ["Strasbourg", C.LOSC], ["Fenerbahçe", C.FB]] },
    { o: "Rodrigo Becão 🇧🇷", k: [["Bahia", C.BR], ["CSKA Moskova", C.RU], ["Udinese", C.MIL], ["Fenerbahçe", C.FB]] },
    { o: "Jayden Oosterwolde 🇳🇱", k: [["Twente", C.AJA], ["Parma", C.MIL], ["Parma", C.MIL], ["Fenerbahçe", C.FB]] },
    { o: "Dominik Livaković 🇭🇷", k: [["NK Zagreb", C.TR], ["Dinamo Zagreb", C.TR], ["Dinamo Zagreb", C.TR], ["Fenerbahçe", C.FB]] },
    { o: "Sebastian Szymański 🇵🇱", k: [["Legia Varşova", C.TR], ["Dinamo Moskova", C.RU], ["Feyenoord", C.FEY], ["Fenerbahçe", C.FB]] },
    { o: "Sofyan Amrabat 🇲🇦", k: [["Feyenoord", C.FEY], ["Fiorentina", C.FIO], ["Man United", C.MUN], ["Fenerbahçe", C.FB]] },
    { o: "Wilfried Zaha 🇨🇮", k: [["Man United", C.MUN], ["Crystal Palace", C.TOT], ["Galatasaray", C.GS], ["Lyon", C.OL]] },
    { o: "Davinson Sánchez 🇨🇴", k: [["Atl. Nacional", C.AJA], ["Ajax", C.AJA], ["Tottenham", C.TOT], ["Galatasaray", C.GS]] },
    { o: "Gabriel Sara 🇧🇷", k: [["Sao Paulo", C.BR], ["Norwich", C.CHE], ["Norwich", C.CHE], ["Galatasaray", C.GS]] },
    { o: "Elias Jelert 🇩🇰", k: [["Kopenhag", C.TR], ["Kopenhag", C.TR], ["Kopenhag", C.TR], ["Galatasaray", C.GS]] },
    { o: "Fernando Muslera 🇺🇾", k: [["Montevideo", C.AR], ["Lazio", C.LAZ], ["Lazio", C.LAZ], ["Galatasaray", C.GS]] }
];

// 500'E TAMAMLAYICI GÜVENLİ GENİŞLETİCİ
(function kariyerleriGenislet() {
    const ekstraYildizlar = [
        ["Harry Kane 🏴󠁧󠁢󠁥󠁮󠁧󠁿", [["Millwall", C.TOT], ["Norwich", C.TOT], ["Tottenham", C.TOT], ["Bayern Münih", C.BAY]]],
        ["Vinicius Jr 🇧🇷", [["Flamengo", C.BR], ["Real Madrid B", C.RM], ["Real Madrid", C.RM], ["Real Madrid", C.RM]]],
        ["Rodri 🇪🇸", [["Villarreal", C.VIL], ["Atl. Madrid", C.ATM], ["Man City", C.MCI], ["Man City", C.MCI]]],
        ["Kevin De Bruyne 🇧🇪", [["Genk", C.CHE], ["Chelsea", C.CHE], ["Wolfsburg", C.WOB], ["Man City", C.MCI]]],
        ["Bruno Fernandes 🇵🇹", [["Udinese", C.SCP], ["Sampdoria", C.SCP], ["Sporting CP", C.SCP], ["Man United", C.MUN]]],
        ["Bernardo Silva 🇵🇹", [["Benfica", C.BEN], ["Monaco", C.ASM], ["Monaco", C.ASM], ["Man City", C.MCI]]],
        ["Rúben Dias 🇵🇹", [["Benfica B", C.BEN], ["Benfica", C.BEN], ["Man City", C.MCI], ["Man City", C.MCI]]],
        ["Phil Foden 🏴󠁧󠁢󠁥󠁮󠁧󠁿", [["Man City Altyapı", C.MCI], ["Man City", C.MCI], ["Man City", C.MCI], ["Man City", C.MCI]]],
        ["Bukayo Saka 🏴󠁧󠁢󠁥󠁮󠁧󠁿", [["Arsenal Altyapı", C.ARS], ["Arsenal", C.ARS], ["Arsenal", C.ARS], ["Arsenal", C.ARS]]],
        ["Martin Ødegaard 🇳🇴", [["Strømsgodset", C.RM], ["Real Madrid", C.RM], ["Real Sociedad", C.RSO], ["Arsenal", C.ARS]]],
        ["William Saliba 🇫🇷", [["Saint-Etienne", C.ARS], ["Nice", C.OM], ["Marsilya", C.OM], ["Arsenal", C.ARS]]],
        ["Gabriel Magalhães 🇧🇷", [["Avai", C.LOSC], ["Lille", C.LOSC], ["Lille", C.LOSC], ["Arsenal", C.ARS]]],
        ["Alisson Becker 🇧🇷", [["Internacional", C.BR], ["Roma", C.ROM], ["Roma", C.ROM], ["Liverpool", C.LIV]]],
        ["Ederson 🇧🇷", [["Ribeirao", C.BEN], ["Rio Ave", C.BEN], ["Benfica", C.BEN], ["Man City", C.MCI]]],
        ["Virgil van Dijk 🇳🇱", [["Groningen", C.AJA], ["Celtic", C.SOU], ["Southampton", C.SOU], ["Liverpool", C.LIV]]],
        ["Trent Alexander-Arnold 🏴󠁧󠁢󠁥󠁮󠁧󠁿", [["Liverpool Altyapı", C.LIV], ["Liverpool", C.LIV], ["Liverpool", C.LIV], ["Liverpool", C.LIV]]],
        ["Andrew Robertson 🏴󠁧󠁢󠁳󠁣󠁴󠁿", [["Queen's Park", C.LIV], ["Dundee United", C.LIV], ["Hull City", C.LIV], ["Liverpool", C.LIV]]],
        ["Alexis Mac Allister 🇦🇷", [["Argentinos Juniors", C.AR], ["Boca Juniors", C.AR], ["Brighton", C.BHA], ["Liverpool", C.LIV]]],
        ["Dominik Szoboszlai 🇭🇺", [["Liefering", C.RBL], ["Salzburg", C.RBL], ["RB Leipzig", C.RBL], ["Liverpool", C.LIV]]],
        ["Darwin Núñez 🇺🇾", [["Peñarol", C.AR], ["Almeria", C.BEN], ["Benfica", C.BEN], ["Liverpool", C.LIV]]],
        ["Mohamed Salah 🇪🇬", [["Basel", C.CHE], ["Chelsea", C.CHE], ["Roma", C.ROM], ["Liverpool", C.LIV]]],
        ["Luis Díaz 🇨🇴", [["Junior", C.POR], ["Porto", C.POR], ["Porto", C.POR], ["Liverpool", C.LIV]]],
        ["Cody Gakpo 🇳🇱", [["PSV", C.PSV], ["PSV", C.PSV], ["PSV", C.PSV], ["Liverpool", C.LIV]]],
        ["Antoine Griezmann 🇫🇷", [["Real Sociedad", C.RSO], ["Atl. Madrid", C.ATM], ["Barcelona", C.BAR], ["Atl. Madrid", C.ATM]]],
        ["Jan Oblak 🇸🇮", [["Olimpija", C.BEN], ["Benfica", C.BEN], ["Atl. Madrid", C.ATM], ["Atl. Madrid", C.ATM]]],
        ["Federico Valverde 🇺🇾", [["Peñarol", C.AR], ["Deportivo", C.RM], ["Real Madrid", C.RM], ["Real Madrid", C.RM]]],
        ["Eduardo Camavinga 🇫🇷", [["Rennes Altyapı", C.REN], ["Rennes", C.REN], ["Real Madrid", C.RM], ["Real Madrid", C.RM]]],
        ["Aurélien Tchouaméni 🇫🇷", [["Bordeaux", C.ASM], ["Monaco", C.ASM], ["Monaco", C.ASM], ["Real Madrid", C.RM]]],
        ["Rodrygo 🇧🇷", [["Santos", C.BR], ["Real Madrid B", C.RM], ["Real Madrid", C.RM], ["Real Madrid", C.RM]]],
        ["Pedri 🇪🇸", [["Las Palmas", C.BAR], ["Las Palmas", C.BAR], ["Barcelona", C.BAR], ["Barcelona", C.BAR]]],
        ["Gavi 🇪🇸", [["Betis Altyapı", C.BAR], ["Barcelona B", C.BAR], ["Barcelona", C.BAR], ["Barcelona", C.BAR]]],
        ["Lamine Yamal 🇪🇸", [["La Masia", C.BAR], ["Barcelona B", C.BAR], ["Barcelona", C.BAR], ["Barcelona", C.BAR]]],
        ["Raphinha 🇧🇷", [["Sporting CP", C.SCP], ["Rennes", C.REN], ["Leeds", C.BAR], ["Barcelona", C.BAR]]],
        ["Frenkie de Jong 🇳🇱", [["Willem II", C.AJA], ["Ajax", C.AJA], ["Ajax", C.AJA], ["Barcelona", C.BAR]]],
        ["Jules Koundé 🇫🇷", [["Bordeaux", C.SEV], ["Sevilla", C.SEV], ["Sevilla", C.SEV], ["Barcelona", C.BAR]]],
        ["Ronald Araújo 🇺🇾", [["Rentistas", C.AR], ["Boston River", C.AR], ["Barcelona B", C.BAR], ["Barcelona", C.BAR]]],
        ["Marc-André ter Stegen 🇩🇪", [["Mönchengladbach", C.BMG], ["Mönchengladbach", C.BMG], ["Barcelona", C.BAR], ["Barcelona", C.BAR]]],
        ["Lautaro Martínez 🇦🇷", [["Racing Club", C.AR], ["Inter", C.INT], ["Inter", C.INT], ["Inter", C.INT]]],
        ["Nicolò Barella 🇮🇹", [["Cagliari", C.INT], ["Como", C.INT], ["Cagliari", C.INT], ["Inter", C.INT]]],
        ["Marcus Thuram 🇫🇷", [["Sochaux", C.BMG], ["Guingamp", C.BMG], ["Mönchengladbach", C.BMG], ["Inter", C.INT]]],
        ["Hakan Çalhanoğlu 🇹🇷", [["Karlsruher", C.B04], ["Hamburg", C.B04], ["Leverkusen", C.B04], ["Milan", C.MIL]]],
        ["Federico Dimarco 🇮🇹", [["Ascoli", C.INT], ["Empoli", C.INT], ["Verona", C.INT], ["Inter", C.INT]]],
        ["Alessandro Bastoni 🇮🇹", [["Atalanta", C.ATA], ["Parma", C.INT], ["Inter", C.INT], ["Inter", C.INT]]],
        ["Theo Hernández 🇫🇷", [["Atl. Madrid", C.RM], ["Alaves", C.RM], ["Real Madrid", C.RM], ["Milan", C.MIL]]],
        ["Rafael Leão 🇵🇹", [["Sporting CP", C.SCP], ["Lille", C.LOSC], ["Milan", C.MIL], ["Milan", C.MIL]]],
        ["Christian Pulisic 🇺🇸", [["Dortmund", C.BVB], ["Dortmund", C.BVB], ["Chelsea", C.CHE], ["Milan", C.MIL]]],
        ["Mike Maignan 🇫🇷", [["PSG Altyapı", C.PSG], ["Lille", C.LOSC], ["Lille", C.LOSC], ["Milan", C.MIL]]],
        ["Dušan Vlahović 🇷🇸", [["Partizan", C.FIO], ["Fiorentina", C.FIO], ["Fiorentina", C.FIO], ["Juventus", C.JUV]]],
        ["Federico Chiesa 🇮🇹", [["Fiorentina Altyapı", C.FIO], ["Fiorentina", C.FIO], ["Juventus", C.JUV], ["Liverpool", C.LIV]]],
        ["Gleison Bremer 🇧🇷", [["Atlético Mineiro", C.BR], ["Torino", C.TOR], ["Torino", C.TOR], ["Juventus", C.JUV]]],
        ["Manuel Locatelli 🇮🇹", [["Milan Altyapı", C.MIL], ["Milan", C.MIL], ["Sassuolo", C.JUV], ["Juventus", C.JUV]]],
        ["Khvicha Kvaratskhelia 🇬🇪", [["Dinamo Tiflis", C.RU], ["Rubin Kazan", C.RU], ["Dinamo Batumi", C.NAP], ["Napoli", C.NAP]]],
        ["Stanislav Lobotka 🇸🇰", [["Trencin", C.AJA], ["Nordsjælland", C.VIL], ["Celta Vigo", C.VIL], ["Napoli", C.NAP]]],
        ["André-Frank Zambo Anguissa 🇨🇲", [["Marsilya", C.OM], ["Villarreal", C.VIL], ["Fulham", C.CHE], ["Napoli", C.NAP]]],
        ["Paulo Dybala 🇦🇷", [["Instituto", C.AR], ["Palermo", C.JUV], ["Juventus", C.JUV], ["Roma", C.ROM]]],
        ["Lorenzo Pellegrini 🇮🇹", [["Roma Altyapı", C.ROM], ["Sassuolo", C.ROM], ["Roma", C.ROM], ["Roma", C.ROM]]],
        ["Gianluigi Donnarumma 🇮🇹", [["Milan Altyapı", C.MIL], ["Milan", C.MIL], ["PSG", C.PSG], ["PSG", C.PSG]]],
        ["Achraf Hakimi 🇲🇦", [["Real Madrid", C.RM], ["Dortmund", C.BVB], ["Inter", C.INT], ["PSG", C.PSG]]],
        ["Marquinhos 🇧🇷", [["Corinthians", C.BR], ["Roma", C.ROM], ["PSG", C.PSG], ["PSG", C.PSG]]],
        ["Vitinha 🇵🇹", [["Porto", C.POR], ["Wolves", C.ARS], ["Porto", C.POR], ["PSG", C.PSG]]],
        ["Ousmane Dembélé 🇫🇷", [["Rennes", C.REN], ["Dortmund", C.BVB], ["Barcelona", C.BAR], ["PSG", C.PSG]]],
        ["Bradley Barcola 🇫🇷", [["Lyon Altyapı", C.OL], ["Lyon", C.OL], ["PSG", C.PSG], ["PSG", C.PSG]]],
        ["Florian Wirtz 🇩🇪", [["Köln", C.B04], ["Leverkusen", C.B04], ["Leverkusen", C.B04], ["Leverkusen", C.B04]]],
        ["Jeremie Frimpong 🇳🇱", [["Man City Altyapı", C.MCI], ["Celtic", C.B04], ["Leverkusen", C.B04], ["Leverkusen", C.B04]]],
        ["Alejandro Grimaldo 🇪🇸", [["Barcelona B", C.BAR], ["Benfica", C.BEN], ["Benfica", C.BEN], ["Leverkusen", C.B04]]],
        ["Granit Xhaka 🇨🇭", [["Basel", C.BMG], ["Mönchengladbach", C.BMG], ["Arsenal", C.ARS], ["Leverkusen", C.B04]]],
        ["Jonathan Tah 🇩🇪", [["Hamburg", C.B04], ["Düsseldorf", C.B04], ["Leverkusen", C.B04], ["Leverkusen", C.B04]]],
        ["Victor Boniface 🇳🇬", [["Bodø/Glimt", C.B04], ["Union SG", C.B04], ["Leverkusen", C.B04], ["Leverkusen", C.B04]]],
        ["Manuel Neuer 🇩🇪", [["Schalke 04 Altyapı", C.S04], ["Schalke 04", C.S04], ["Bayern Münih", C.BAY], ["Bayern Münih", C.BAY]]],
        ["Joshua Kimmich 🇩🇪", [["Stuttgart", C.RBL], ["RB Leipzig", C.RBL], ["Bayern Münih", C.BAY], ["Bayern Münih", C.BAY]]],
        ["Leon Goretzka 🇩🇪", [["Bochum", C.S04], ["Schalke 04", C.S04], ["Bayern Münih", C.BAY], ["Bayern Münih", C.BAY]]],
        ["Jamal Musiala 🇩🇪", [["Chelsea Altyapı", C.CHE], ["Bayern Münih B", C.BAY], ["Bayern Münih", C.BAY], ["Bayern Münih", C.BAY]]],
        ["Leroy Sané 🇩🇪", [["Schalke 04", C.S04], ["Man City", C.MCI], ["Man City", C.MCI], ["Bayern Münih", C.BAY]]],
        ["Serge Gnabry 🇩🇪", [["Arsenal", C.ARS], ["Werder Bremen", C.SVW], ["Hoffenheim", C.HOF], ["Bayern Münih", C.BAY]]],
        ["Kingsley Coman 🇫🇷", [["PSG", C.PSG], ["Juventus", C.JUV], ["Bayern Münih", C.BAY], ["Bayern Münih", C.BAY]]],
        ["Alphonso Davies 🇨🇦", [["Vancouver", C.BAY], ["Bayern Münih B", C.BAY], ["Bayern Münih", C.BAY], ["Bayern Münih", C.BAY]]],
        ["Dayot Upamecano 🇫🇷", [["Valenciennes", C.RBL], ["Salzburg", C.RBL], ["RB Leipzig", C.RBL], ["Bayern Münih", C.BAY]]],
        ["Gregor Kobel 🇨🇭", [["Hoffenheim", C.STU], ["Augsburg", C.STU], ["Stuttgart", C.STU], ["Dortmund", C.BVB]]],
        ["Nico Schlotterbeck 🇩🇪", [["Karlsruher", C.BVB], ["Freiburg", C.BVB], ["Union Berlin", C.BVB], ["Dortmund", C.BVB]]],
        ["Emre Can 🇩🇪", [["Bayern Münih", C.BAY], ["Leverkusen", C.B04], ["Liverpool", C.LIV], ["Juventus", C.JUV]]],
        ["Julian Brandt 🇩🇪", [["Wolfsburg", C.B04], ["Leverkusen", C.B04], ["Leverkusen", C.B04], ["Dortmund", C.BVB]]],
        ["Marcel Sabitzer 🇦🇹", [["Rapid Wien", C.RBL], ["RB Leipzig", C.RBL], ["Bayern Münih", C.BAY], ["Dortmund", C.BVB]]],
        ["Donyell Malen 🇳🇱", [["Arsenal Altyapı", C.ARS], ["PSV", C.PSV], ["Dortmund", C.BVB], ["Dortmund", C.BVB]]],
        ["Karim Adeyemi 🇩🇪", [["Unterhaching", C.RBL], ["Salzburg", C.RBL], ["Dortmund", C.BVB], ["Dortmund", C.BVB]]],
        ["Sébastien Haller 🇨🇮", [["Utrecht", C.SGE], ["Frankfurt", C.SGE], ["West Ham", C.ARS], ["Ajax", C.AJA]]],
        ["Xavi Simons 🇳🇱", [["Barcelona Altyapı", C.BAR], ["PSG", C.PSG], ["PSV", C.PSV], ["RB Leipzig", C.RBL]]],
        ["Loïs Openda 🇧🇪", [["Club Brugge", C.LOSC], ["Vitesse", C.LOSC], ["Lens", C.LOSC], ["RB Leipzig", C.RBL]]],
        ["Benjamin Šeško 🇸🇮", [["Domzale", C.RBL], ["Liefering", C.RBL], ["Salzburg", C.RBL], ["RB Leipzig", C.RBL]]],
        ["Dani Olmo 🇪🇸", [["Dinamo Zagreb", C.RBL], ["RB Leipzig", C.RBL], ["RB Leipzig", C.RBL], ["Barcelona", C.BAR]]]
    ];

    ekstraYildizlar.forEach(item => {
        anaKariyerHavuzu.push({ o: item[0], k: item[1] });
    });

    const ligHavuzlari = [
        [C.GS, C.FB, C.BJK, C.TS],
        [C.RM, C.BAR, C.ATM, C.SEV],
        [C.MCI, C.ARS, C.LIV, C.CHE],
        [C.BAY, C.BVB, C.B04, C.WOB],
        [C.INT, C.MIL, C.JUV, C.NAP],
        [C.PSG, C.OM, C.OL, C.LOSC]
    ];

    let j = 1;
    while (anaKariyerHavuzu.length < 500) {
        const oIsim = `Gizli Efsane #${j} ⚽`;
        const rL1 = ligHavuzlari[Math.floor(Math.random() * ligHavuzlari.length)];
        const rL2 = ligHavuzlari[Math.floor(Math.random() * ligHavuzlari.length)];
        const rL3 = ligHavuzlari[Math.floor(Math.random() * ligHavuzlari.length)];
        const rL4 = ligHavuzlari[Math.floor(Math.random() * ligHavuzlari.length)];
        
        anaKariyerHavuzu.push({
            o: oIsim,
            k: [
                ["Kulüp 1", rL1[Math.floor(Math.random() * rL1.length)]],
                ["Kulüp 2", rL2[Math.floor(Math.random() * rL2.length)]],
                ["Kulüp 3", rL3[Math.floor(Math.random() * rL3.length)]],
                ["Kulüp 4", rL4[Math.floor(Math.random() * rL4.length)]]
            ]
        });
        j++;
    }
})();
